class_name CitySim
extends RefCounted

## Pure city simulation — no engine, scene or rendering dependencies, so it can
## be advanced deterministically and unit-tested in isolation. The view layer
## reads this simulation; the simulation never reads the view.
## (See CLAUDE.md: keep the simulation core decoupled from the view.)
##
## The city is a row of build slots that unlock as population grows (#16). Each
## slot is empty or holds one zone. Economic zones move money/population (#13-15)
## and cost monthly upkeep (#17). Five indicators (#19) decay over time (#23),
## are propped up by their matching service zone (#24), and energy drains faster
## the bigger the city (#22). Happiness is their average (#20) and steers
## immigration/revenue (#21).

enum Zone {
	RESIDENTIAL, COMMERCIAL, INDUSTRIAL,
	POLICE, SCHOOL, HOSPITAL, ROADS, POWER,
}

enum Indicator { SECURITY, EDUCATION, HEALTH, TRAFFIC, ENERGY }

const INDICATORS := [
	Indicator.SECURITY, Indicator.EDUCATION, Indicator.HEALTH,
	Indicator.TRAFFIC, Indicator.ENERGY,
]

## Service zone that boosts each indicator.
const SERVICE_FOR := {
	Indicator.SECURITY: Zone.POLICE,
	Indicator.EDUCATION: Zone.SCHOOL,
	Indicator.HEALTH: Zone.HOSPITAL,
	Indicator.TRAFFIC: Zone.ROADS,
	Indicator.ENERGY: Zone.POWER,
}

# --- Economy (provisional — see GDD balancing) ---
const COMMERCIAL_REVENUE := 2.0
const INDUSTRIAL_REVENUE := 1.5
const RESIDENTIAL_POP := 1.0 / 3.0  # +1 resident every 3s

const ZONE_COST := {
	Zone.RESIDENTIAL: 500.0, Zone.COMMERCIAL: 800.0, Zone.INDUSTRIAL: 1000.0,
	Zone.POLICE: 1500.0, Zone.SCHOOL: 1500.0, Zone.HOSPITAL: 1500.0,
	Zone.ROADS: 1200.0, Zone.POWER: 1800.0,
}
const ZONE_UPKEEP := {  # per in-game month
	Zone.RESIDENTIAL: 10.0, Zone.COMMERCIAL: 20.0, Zone.INDUSTRIAL: 40.0,
	Zone.POLICE: 80.0, Zone.SCHOOL: 80.0, Zone.HOSPITAL: 80.0,
	Zone.ROADS: 60.0, Zone.POWER: 100.0,
}
const MONTH := 30.0  # seconds per in-game month

const BASE_SLOTS := 4
const POP_PER_SLOT := 100.0

# --- Indicators ---
const INDICATOR_START := 60.0  # a fresh city starts stable, not yet booming
const BASE_DECAY := 0.05               # -1 point / 20s
const SERVICE_BOOST := 0.5             # +0.5/s per matching service
const INDUSTRY_HEALTH_PENALTY := 0.1   # extra health decay per industrial zone
const ENERGY_DEMAND := 0.05            # extra energy decay per consuming building
const ENERGY_SUPPLY := 0.6             # energy gain per power plant

# --- Happiness thresholds ---
const HAPPY_HIGH := 70.0
const HAPPY_LOW := 40.0

var money: float
var population: float
var revenue_per_sec: float
var upkeep_per_sec: float
var pop_per_sec: float
var indicators := {}  # Indicator -> float (0..100)

var slots: Array = []  # each entry is a Zone value, or null when empty

func _init(starting_money: float = 1000.0) -> void:
	money = starting_money
	population = 0.0
	for ind in INDICATORS:
		indicators[ind] = INDICATOR_START
	_sync_slots()
	_recompute_rates()

## Number of slots currently available to build on.
func unlocked_slots() -> int:
	return BASE_SLOTS + int(population / POP_PER_SLOT)

func can_build(zone: Zone, slot_index: int) -> bool:
	return slot_index >= 0 and slot_index < slots.size() \
		and slots[slot_index] == null \
		and money >= ZONE_COST[zone]

## Build a zone into an empty unlocked slot. Returns false (no-op) if the slot
## is taken/locked or there isn't enough money.
func build(zone: Zone, slot_index: int) -> bool:
	if not can_build(zone, slot_index):
		return false
	money -= ZONE_COST[zone]
	slots[slot_index] = zone
	_recompute_rates()
	return true

func zone_count(zone: Zone) -> int:
	var n := 0
	for s in slots:
		if s == zone:
			n += 1
	return n

## Average of the five indicators (#20).
func happiness() -> float:
	var total := 0.0
	for ind in INDICATORS:
		total += indicators[ind]
	return total / INDICATORS.size()

func net_per_sec() -> float:
	return revenue_per_sec * _revenue_factor() - upkeep_per_sec

## Advance the simulation by `delta` seconds.
func advance(delta: float) -> void:
	money += (revenue_per_sec * _revenue_factor() - upkeep_per_sec) * delta
	population = maxf(0.0, population + pop_per_sec * _pop_factor() * delta)
	for ind in INDICATORS:
		indicators[ind] = clampf(indicators[ind] + _indicator_rate(ind) * delta, 0.0, 100.0)
	_sync_slots()

# --- internals ---

func _sync_slots() -> void:
	while slots.size() < unlocked_slots():
		slots.append(null)

func _recompute_rates() -> void:
	revenue_per_sec = zone_count(Zone.COMMERCIAL) * COMMERCIAL_REVENUE \
		+ zone_count(Zone.INDUSTRIAL) * INDUSTRIAL_REVENUE
	pop_per_sec = zone_count(Zone.RESIDENTIAL) * RESIDENTIAL_POP
	var upkeep := 0.0
	for s in slots:
		if s != null:
			upkeep += ZONE_UPKEEP[s]
	upkeep_per_sec = upkeep / MONTH

func _indicator_rate(ind: Indicator) -> float:
	if ind == Indicator.ENERGY:
		# Energy is generated by power plants and consumed by every other
		# building, so it drains faster the bigger the city gets (#22).
		return zone_count(Zone.POWER) * ENERGY_SUPPLY \
			- (BASE_DECAY + _consuming_count() * ENERGY_DEMAND)
	var boost := zone_count(SERVICE_FOR[ind]) * SERVICE_BOOST
	var decay := BASE_DECAY
	if ind == Indicator.HEALTH:
		decay += zone_count(Zone.INDUSTRIAL) * INDUSTRY_HEALTH_PENALTY
	return boost - decay

func _consuming_count() -> int:
	var n := 0
	for s in slots:
		if s != null and s != Zone.POWER:
			n += 1
	return n

func _revenue_factor() -> float:
	var h := happiness()
	if h >= HAPPY_HIGH:
		return 1.2
	if h < HAPPY_LOW:
		return 0.7
	return 1.0

func _pop_factor() -> float:
	var h := happiness()
	if h >= HAPPY_HIGH:
		return 1.5   # immigration
	if h < HAPPY_LOW:
		return -1.0  # emigration
	return 1.0
